apiVersion: apps/v1
kind: Deployment
metadata:
  name: register
  labels:
    app: register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
        - name: register
          image: ezehm/register
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: register
  labels:
    app: register
spec:
  ports:
    - port: 8081
      protocol: TCP
  selector:
    appdb: register